### ISSUE TITLE
Uncaught ReferenceError: path is not defined

### ISSUE THREAD

**Issue by ashokpv** [wontem/atom-go-to-file#3]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Ubuntu 14.04.5
**Thrown From**: [go-to-file](https://github.com/wontem/atom-go-to-file) package 0.2.0

### Stack Trace

Uncaught ReferenceError: path is not defined

```
At /home/ashok/.atom/packages/go-to-file/lib/go-to-file-view.coffee:5

ReferenceError: path is not defined
    at /packages/go-to-file/lib/go-to-file-view.coffee:5:11
    at /packages/go-to-file/lib/go-to-file-view.coffee:3:19)
    at /packages/go-to-file/lib/go-to-file-view.coffee:1:1)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /packages/go-to-file/lib/main.coffee:2:16)
    at /packages/go-to-file/lib/main.coffee:1:1)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/app.asar/src/package.js:796:27)
    at Package.module.exports.Package.activateConfig (/app.asar/src/package.js:266:12)
    at PackageManager.module.exports.PackageManager.packageHasSettings (/app.asar/node_modules/settings-view/lib/package-manager.js:53:14)
    at PackageCard.module.exports.PackageCard.hasSettings (/app.asar/node_modules/settings-view/lib/package-card.js:728:34)
    at PackageCard.module.exports.PackageCard.updateSettingsState (/app.asar/node_modules/settings-view/lib/package-card.js:402:16)
    at PackageCard.module.exports.PackageCard.updateInterfaceState (/app.asar/node_modules/settings-view/lib/package-card.js:395:12)
    at /app.asar/node_modules/settings-view/lib/package-card.js:665:24
    at /app.asar/node_modules/settings-view/lib/package-card.js:741:20
    at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at PackageManager.module.exports.PackageManager.emitPackageEvent (/app.asar/node_modules/settings-view/lib/package-manager.js:652:27)
    at /app.asar/node_modules/settings-view/lib/package-manager.js:491:26
    at exit (/app.asar/node_modules/settings-view/lib/package-manager.js:99:16)
    at triggerExitCallback (/app.asar/src/buffered-process.js:322:11)
    at /app.asar/src/buffered-process.js:343:11
    at /app.asar/src/buffered-process.js:204:9)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:493:12)
```

### Commands

```
     -9:01.3.0 core:backspace (input.hidden-input)
  2x -8:59.5.0 core:confirm (input.hidden-input)
 37x -7:40.5.0 core:move-down (input.hidden-input)
     -6:32.9.0 golang:update-tools (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
undefined -5:47.3.0 core:move-down (input.hidden-input)
 39x -5:30.3.0 core:move-up (input.hidden-input)
  2x -2:53 core:save (input.hidden-input)
     -2:05.2.0 core:confirm (input.hidden-input)
     -1:05.1.0 tree-view:reveal-active-file (div.line)
     -0:55.5.0 go-to-file:toggle (input.hidden-input)
     -0:53.7.0 core:paste (div.line)
     -0:50.7.0 core:undo (input.hidden-input)
     -0:44.5.0 symbols-view:go-to-declaration (span.syntax--support.syntax--function.syntax--go)
     -0:40 go-to-file:toggle (span.syntax--support.syntax--function.syntax--go)
     -0:33.7.0 tree-view:show-current-file-in-file-manager (span.syntax--support.syntax--function.syntax--go)
  2x -0:28.1.0 go-to-file:toggle (span.syntax--support.syntax--function.syntax--go)
```

### Non-Core Packages

```
go-debug 1.1.0 
go-plus 5.3.3 
go-to-file 0.2.0 
linter 2.1.0 
linter-golinter 1.2.1 
```

**Comment by Jetinho** [comment]
Hi, I am facing a similar issue : did you manage to solve that problem and get the package working ?
